### PR TITLE
fixes to windows build

### PR DESCRIPTION
**Pull request by zediir**
Fixes errors in windows build

### CODE REVIEW

**Comment by marcocalignano** [comment]
@zediir Please rebase it on my new code (just committed) and please test again.

**Comment by marcocalignano** [comment]
If you make the PR after rebase I can merge it!

**Comment by zediir** [comment]
Sure. I'm in town right now but I'll have it done soonish.

**Comment by zediir** [comment]
rebased

**Comment by marcocalignano** [comment]
So now can you test again all three options please. 
I have plans this evening no Idea how long I am home still. In the worst case I see you test tomorrow. 
Thank you very much.

**Pull request merged**
