### PR TITLE
eliminate possible duplicate uploads/resumed games and redundant server connection attempts

### PR DESCRIPTION
**Pull request by alreadydone**
(1) Rename curl_save*.bin to curl_save*.bin0 before attempting game data upload (sendCurl); If upload fails, rename back, and do not try to upload other saved game data.
(If multiple autogtp instances open the same file (which I think should be possible with ReadOnly), renaming should only succeed after all but one instance have closed the file, if I understand this correctly.)

(2) When removing storefile in getWork, check whether the file has already been removed. If it's removed then it's picked up by another autogtp instance and we proceed to the next storefile.

(3) Introduce a global bool variable networkConnectionFailure in Management.cpp. In getWork, do not attempt to connect to server to get new job if sendAllGames already caught a network exception (which set the variable to be true); set the variable to be false and check whether connection is restored after one game is played.
(I originally introduced the variable in main.cpp, but later removed it, so main.cpp remains changed in the end.)

I haven't tested my changes but maybe you can tell whether they work with your expertise.

### CODE REVIEW

**Comment by marcocalignano** [comment]
@alreadydone The rename (depending on the OS) can work even if a file is open by another process. So the rename 'trick' does not work. The remove trick can work but it is just a trick and personally I do not like it. 
There is a much more elegant solution, that also prevent other concurrency problems, that we can implement. We should just use QLockFile. This is exactly what we need and we should use it even when we save the files (avoiding that a process start to resume a game the another process did not saved completely yet).

**Comment by marcocalignano** [comment]
@alreadydone So go on my repository on the branch /fileLocks and please test if that branch is good for what you are doing if you find it good I will make a PR.

**Comment by alreadydone** [comment]
@marcocalignano Does `QLockFile("abc.lock");` locks the file `abc`? I can't see this from the documentation. My understanding is that you should just do `QLockFile("abc");`.

**Comment by alreadydone** [comment]
> The rename (depending on the OS) can work even if a file is open by another process. 

If that's the case, after one process has renamed the file, I think the other process will fail to rename it and rename() will return false because (1) the file to be renamed no longer exists (not sure about this), and (2) the renamed file already exists (see [documentation](http://doc.qt.io/qt-5/qfile.html#rename)). In any case only one process will proceed to resume the game. (Note: file will be closed before renaming.)

I continue with the renaming approach: my latest commit deals with saving curl_save*.bin files. I agree that QLockFile (which I wasn't aware of) is more elegant but I am content with my approach since it requires minimal changes to the code.

**Comment by marcocalignano** [comment]
QLockFile is like a mutex and the name of the file is like the pointer to the mutex. So if a process lock the QLockFile "abc.lock" another process cannot lock the same QLockFile and has to wait till the first process unlock it. To create the QLockFile I use the name of the file I will read to load the game plus the extension ".lock". If another file wants to read the same file will try to lock the same QLockFile like the first process and since is already locked will go to the next one. Like that I do not have to rename or load file into memory that then later I have to forget only because one was faster than me.

**Comment by alreadydone** [comment]
OK, my other comment about switching the order is also invalid then, and your code should work fine. I think you haven't done all relevant changes yet, and you probably want to merge some of my commits above (https://github.com/marcocalignano/leela-zero/pull/5/commits/e99ee9da3c6e564020f4bc9d0f448373839ec5a0, some of https://github.com/marcocalignano/leela-zero/pull/5/commits/90f6e7127c7cf44d4272b9adfc3562ef5dde9011, https://github.com/marcocalignano/leela-zero/pull/5/commits/e1847fc5d6f496e3bd4bf8f1bfb15e52fdf7e45a, and https://github.com/marcocalignano/leela-zero/pull/5/commits/70d84e1b129c79d256ab292163b78890b67a85d8). I now believe that your approach is the standard and correct way to use QLockFile which was just unintuitive to me.

**Comment by marcocalignano** [comment]
>  I think you haven't done all relevant changes yet

It is true I synchronize only the store load game when they are interrupted, what is missing are the save and load files for upload in case of connection failure.
But anyway the commit e99ee9d is not good. I want to try to send all the save game next time I finish a game. Usually, for the normal user 10 min or more are passed since then so the server or the connection might be back up. Maybe we can think of an option for you the just retry once and not 4 times.
And like I said the other three are solved with the QLockFiles without checking for concurrent removal or renaming files when I do not really need them.

**Comment by marcocalignano** [comment]
@alreadydone Pull the /lockFiles branch again, now it should be all done. And if you can test it would be really cool!

**Comment by alreadydone** [comment]
> It is true I synchronize only the store load game when they are interrupted, what is missing are the save and load files for upload in case of connection failure.

Yes, I see both are done now.

> But anyway the commit e99ee9d is not good. I want to try to send all the save game next time I finish a game. Usually, for the normal user 10 min or more are passed since then so the server or the connection might be back up. Maybe we can think of an option for you the just retry once and not 4 times.

I think e99ee9d did exactly this. The flow is getWork -> 10 min for a game -> uploadData or uploadResult -> sendAllGames -> getWork. I introduced the global variable `networkConnectionFailure` which is false by default, and should be reset to false at the beginning of `uploadData` and `uploadResult`. The `catch` inside `uploadData`, `uploadResult` and `sendAllGames` should set `networkConnectionFailure = true`, and we should not then attempt connection anymore in `sendAllGames` or `getWork`. ~~Notice there will be 3 retries only if the connection succeeded in `uploadData` and/or `sendAllGames` but fails in `getWork`, so they are not very likely.~~ 4 retries are too many with multiple instances running, but maybe I'll just remember to set `MAX_RETRIES = 0` when compiling, and you can keep the setting for the official release.

If you agree that this works I'll make another PR and close this one. This one is not good enough because I reset `networkConnectionFailure` at beginning of sendAllGames, and didn't do the changes in `uploadData` and `uploadResult`. I wonder whether there will be a problem if `uploadData` succeeds but `uploadResult` fails.

BTW I seem to find a problem when looking at the retry code. https://github.com/marcocalignano/leela-zero/blob/77271e69d244ae5531ef5ca32977ba3ace80c558/autogtp/Management.cpp#L428 
(There are two other places.) It seems that you only do three tries, not three retries. The last "retry" wait for 67 seconds but doesn't do anything, directly displaying the message "Maximum number of retries exceeded..." right away after 67 seconds are passed.

I am also curious what this is doing:
https://github.com/marcocalignano/leela-zero/blob/77271e69d244ae5531ef5ca32977ba3ace80c558/autogtp/Management.cpp#L621

**Comment by marcocalignano** [comment]
First you have only UploadData() or UploadResult() depending on what game just finished.
Setting the networkConnectionFailure = true could be good but only to avoid sendAllGames, the getWork() I want to have it retry before going into a fallback case. Plus in getWork() you have to set networkConnectionFailure = false so after the game is finished you try again the UploadData() or UploadResult(). 

Like you said the retry code is flowed I can fix it this evening and the I can add a --no-retry option so it tries only once to send or receive data. 

If you compile your version set MAX_RETRY = 1 otherwise it won't enter the for loos at all. (also flow that I have to fix).

**Comment by alreadydone** [comment]
I'd like to do the tests but I may be slow (I can't run `autogtp -g 2` and have to wait for jobs to be started by the scheduler). I designed the following tests which should not be hard for you to do:
- Modify Management.cpp slightly so that uploadData and uploadResult go directly to saveCurl (and comment out sendAllGames in getResult). Run `autogtp -g 20 -s` (or `-m 20`?) to gather 20 curl_save*.bin in the same directory. Then run `autogtp & autogtp & autogtp`; each of the three `autogtp` instances should pick up some of the curl_save*bin to upload, and in the console output there should be exactly 20 "stored in database" messages without repetitions.

- Without modifying Management.cpp, run `autogtp -g 20 -t 1` to gather 20 storefile*.bin in the same directory. Then run `autogtp & autogtp & autogtp & autogtp & ...`; each of the instances should pick up one game to resume and there should be no repetitions. If you run 20 instances, all storefile*.bin should disappear soon. You may decrease 20 to a smaller number as well.

These can't test whether a problem will occur when one instance is reading and another is writing; I don't have an easy way to produce such coincidence in timing without of running hundreds of instances. But new jobs submitted to Big Red II will run the fileLocks version, so over time we'll see whether everything is working reliably.

**Comment by marcocalignano** [comment]
@alreadydone Test passed, thanks for the ideas. Now I coordinate with @gcp for a PR so maybe we manage to have this in the new release.

**Pull request closed without merging**
